apiVersion: v1
kind: Secret
metadata:
  name: garden-planner-secrets
  namespace: default
  labels:
    app: garden-planner
    component: security
  annotations:
    kubernetes.io/description: "Contains sensitive configuration for Garden Planner application"
    reloader.stakater.com/auto: "true"
type: Opaque
data:
  # JWT Authentication Configuration
  JWT_PRIVATE_KEY: ${BASE64_JWT_PRIVATE_KEY}
  JWT_PUBLIC_KEY: ${BASE64_JWT_PUBLIC_KEY}
  JWT_SECRET: ${BASE64_JWT_SECRET}
  JWT_EXPIRATION: MjRo  # Base64 encoded "24h"
  JWT_REFRESH_EXPIRATION: N2Q=  # Base64 encoded "7d"
  JWT_ALGORITHM: SFMyNTY=  # Base64 encoded "HS256"
  JWT_ISSUER: Z2FyZGVuLXBsYW5uZXItYXBp  # Base64 encoded "garden-planner-api"
  JWT_AUDIENCE: Z2FyZGVuLXBsYW5uZXItY2xpZW50  # Base64 encoded "garden-planner-client"

  # Data Encryption Configuration
  ENCRYPTION_KEY: ${BASE64_ENCRYPTION_KEY}
  ENCRYPTION_IV: ${BASE64_ENCRYPTION_IV}
  ENCRYPTION_SALT: ${BASE64_ENCRYPTION_SALT}
  ENCRYPTION_ALGORITHM: YWVzLTI1Ni1nY20=  # Base64 encoded "aes-256-gcm"
  ENCRYPTION_KEY_LENGTH: MzI=  # Base64 encoded "32"
  ENCRYPTION_IV_LENGTH: MTY=  # Base64 encoded "16"
  ENCRYPTION_SALT_LENGTH: NjQ=  # Base64 encoded "64"
  ENCRYPTION_ITERATIONS: MTAwMDAw  # Base64 encoded "100000"
  ENCRYPTION_DIGEST: c2hhNTEy  # Base64 encoded "sha512"

  # Firebase Cloud Messaging Configuration
  FCM_SERVICE_ACCOUNT_KEY: ${BASE64_FCM_SERVICE_ACCOUNT_JSON}
  FCM_API_KEY: ${BASE64_FCM_API_KEY}
  FCM_PROJECT_ID: ${BASE64_FCM_PROJECT_ID}
  FCM_CLIENT_EMAIL: ${BASE64_FCM_CLIENT_EMAIL}
  FCM_PRIVATE_KEY: ${BASE64_FCM_PRIVATE_KEY}
  FCM_CLIENT_ID: ${BASE64_FCM_CLIENT_ID}
  FCM_AUTH_URI: ${BASE64_FCM_AUTH_URI}
  FCM_TOKEN_URI: ${BASE64_FCM_TOKEN_URI}

  # FCM Delivery Settings
  FCM_MAX_BATCH_SIZE: MTAw  # Base64 encoded "100"
  FCM_MAX_CONCURRENT_BATCHES: NQ==  # Base64 encoded "5"
  FCM_DELIVERY_TIMEOUT: MTAwMA==  # Base64 encoded "1000"
  FCM_MAX_RETRIES: Mw==  # Base64 encoded "3"

  # Database Credentials
  DB_USERNAME: ${BASE64_DB_USERNAME}
  DB_PASSWORD: ${BASE64_DB_PASSWORD}
  DB_ROOT_PASSWORD: ${BASE64_DB_ROOT_PASSWORD}
  DB_CONNECTION_STRING: ${BASE64_DB_CONNECTION_STRING}
  DB_SSL_CERT: ${BASE64_DB_SSL_CERT}